2023-03-28 23:09:30,865 - ERROR - Internal Server Error: /news/ - F:\FULLSTACK\Practice\News Portal\venv\lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('posts1123.html, news/post_list.html'), <traceback object at 0x000001C1DE9BF280>)
Traceback (most recent call last):
  File "F:\FULLSTACK\Practice\News Portal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "F:\FULLSTACK\Practice\News Portal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "F:\FULLSTACK\Practice\News Portal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "F:\FULLSTACK\Practice\News Portal\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "F:\FULLSTACK\Practice\News Portal\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "F:\FULLSTACK\Practice\News Portal\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: posts1123.html, news/post_list.html
2023-03-28 23:09:31,733 - ERROR - "GET /news/ HTTP/1.1" 500 145 - F:\FULLSTACK\Practice\News Portal\venv\lib\site-packages\django\core\servers\basehttp.py - None
